EXCLUDED_PHRASES = [
    "objective study aimed",
    "research needed to understand",
    "despite facing",
    "play significant role shaping",
    "crucial role in shaping",
    "study aims to explore",
    "notable works include",
    "consider factors like",
    "today's fast paced world",
    "expressed excitement",
    "highlights importance considering",
    "emphasizing importance",
    "making it challenging",
    "aims to enhance",
    "study sheds light",
    "emphasizing need",
    "today's digital age",
    "explores themes",
    "address issues like",
    "highlighting the need",
    "study introduce",
    "notable figures",
    "gain valuable insights",
    "showing promising results",
    "media plays a significant role",
    "shared insights",
    "ensure long term success",
    "make a positive impact on the world",
    "facing criticism",
    "providing insights",
    "emphasized importance",
    "indicating potential",
    "struggles faced",
    "secured win",
    "secure win",
    "potentially leading",
    "showcasing",
    "remarked",
    "aligns",
    "surpassing",
    "tragically",
    "impacting",
    "prioritize",
    "sparking",
    "standout",
    "prioritizing",
    "hindering",
    "advancements",
    "aiding",
    "fostering"
]
